[workspace]
members = [
  "crates/*",
]

resolver = "2"

[workspace.dependencies]
# internal dependencies
entity = { path = "./crates/entity"}
grpc = { path = "./crates/grpc"}
migration = { path = "./crates/migration"}
sra = { path = "./crates/sra"}
# external dependencies
clap = { version = "4.5", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
tonic = "0.12"
tonic_types = "0.12"
prost = "0.13"
tonic-build = "0.12"
sea-orm = { version = "1.0.0-rc.7", features = [ "sqlx-sqlite", "runtime-tokio-native-tls", "macros", "with-time", "with-json", "with-uuid"] }
sea-orm-migration = { version = "1.0.0-rc.7", features = [ "sqlx-sqlite", "runtime-tokio-native-tls"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
