[config]
default_to_workspace = false

[tasks.nuke_gen]
dependencies = [
  "rm_db",
  "gen"
]

[tasks.gen]
command = "sea-orm-cli"
args = [
  "generate",
  "entity",
  "--lib",
  "--with-serde=both",
  "--date-time-crate=time",
  # "--ignore-tables",
  "--output-dir=crates/entity/src"
]
dependencies = [
  "gen_message",
  "migrate"
]

[tasks.gen_message]
command = "echo"
args = [ "\n==== generating entities from db.sqlite!!! ===\n" ]

[tasks.migrate]
command = "cargo"
args = ["run", "--package", "migration", "up"]


[tasks.rm_db]
command = "rm"
args = ["db.sqlite"]

# one shot tasks
[tasks.new_migration]
command = "./scripts/new_migration"

