[workspace]
members = [
  ".",
  "scripts/new_migration"
]

[workspace.dependencies]
clap = { version = "4.5", features = ["derive", "cargo", "wrap_help", "unicode", "string", "unstable-styles"] }
rusqlite = { version = "0.31.0", features = ["bundled", "time", "uuid"] }
rusqlite_migration = { version = "1.2", features = [ "from-directory"] }
dirs = "5.0.1"
serde_json = "1"
serde = { version = "1.0", features = ["derive"] }
anyhow = "1.0.86"
dialoguer = "0.11.0"
include_dir = "0.7.4"
time = { version = "0.3.36", features = ["parsing", "formatting", "macros"]}
resolve-path = "0.1.0"
normalize-path = "0.2.1"
uuid = { version = "1.10.0", features = ["v4"] }

[package]
name = "spbased-cli"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
clap = { workspace = true }
rusqlite = { workspace = true }
rusqlite_migration = { workspace = true }
dirs = { workspace = true }
serde_json = { workspace = true }
serde = { workspace = true }
anyhow = { workspace = true }
dialoguer = { workspace = true }
include_dir = { workspace = true }
resolve-path = { workspace = true }
normalize-path = { workspace = true }
time = { workspace = true }
uuid = { workspace = true }
