//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "review_item"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Serialize, Deserialize)]
pub struct Model {
    pub name: String,
    pub create_time: String,
    pub update_time: String,
    pub status: i32,
    pub difficulty: f64,
    pub stability: f64,
    pub next_review_date: String,
    pub item_type: String,
    pub url: String,
    pub data: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Name,
    CreateTime,
    UpdateTime,
    Status,
    Difficulty,
    Stability,
    NextReviewDate,
    ItemType,
    Url,
    Data,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Name,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = String;
    fn auto_increment() -> bool {
        false
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    ReviewEventLog,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Name => ColumnType::String(None).def(),
            Self::CreateTime => ColumnType::String(None).def(),
            Self::UpdateTime => ColumnType::String(None).def(),
            Self::Status => ColumnType::Integer.def(),
            Self::Difficulty => ColumnType::Double.def(),
            Self::Stability => ColumnType::Double.def(),
            Self::NextReviewDate => ColumnType::String(None).def(),
            Self::ItemType => ColumnType::String(None).def(),
            Self::Url => ColumnType::String(None).def(),
            Self::Data => ColumnType::String(None).def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::ReviewEventLog => Entity::has_many(super::review_event_log::Entity).into(),
        }
    }
}

impl Related<super::review_event_log::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ReviewEventLog.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
