//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0-rc.7

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "review_item_type")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub r#type: String,
    pub created: TimeDateTime,
    pub updated: TimeDateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_one = "super::review_item::Entity")]
    ReviewItem,
}

impl Related<super::review_item::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ReviewItem.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
