//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "review_event_log")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub review_item_id: i32,
    pub scheduled_date: String,
    pub review_date: String,
    pub grade: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::review_item::Entity",
        from = "Column::ReviewItemId",
        to = "super::review_item::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ReviewItem,
}

impl Related<super::review_item::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ReviewItem.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
