//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

use sea_orm::{entity::prelude::*, ActiveValue};
use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "review_item"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Serialize, Deserialize)]
pub struct Model {
    pub name: String,
    pub create_time: String,
    pub update_time: String,
    pub status: String,
    pub difficulty: f64,
    pub stability: f64,
    pub last_review_date: String,
    pub next_review_date: String,
    pub item_type: String,
    pub url: String,
    pub data: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Name,
    CreateTime,
    UpdateTime,
    Status,
    Difficulty,
    Stability,
    LastReviewDate,
    NextReviewDate,
    ItemType,
    Url,
    Data,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Name,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = String;
    fn auto_increment() -> bool {
        false
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    ReviewEventLog,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Name => ColumnType::String(None).def(),
            Self::CreateTime => ColumnType::String(None).def(),
            Self::UpdateTime => ColumnType::String(None).def(),
            Self::Status => ColumnType::String(None).def(),
            Self::Difficulty => ColumnType::Double.def(),
            Self::Stability => ColumnType::Double.def(),
            Self::LastReviewDate => ColumnType::String(None).def(),
            Self::NextReviewDate => ColumnType::String(None).def(),
            Self::ItemType => ColumnType::String(None).def(),
            Self::Url => ColumnType::String(None).def(),
            Self::Data => ColumnType::String(None).def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::ReviewEventLog => Entity::has_many(super::review_event_log::Entity).into(),
        }
    }
}

impl Related<super::review_event_log::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ReviewEventLog.def()
    }
}

#[async_trait::async_trait]
impl ActiveModelBehavior for ActiveModel {
    fn new() -> Self {
        Self {
            status: ActiveValue::Set(common::ReviewItemStatus::Inbox.to_string()),
            difficulty: ActiveValue::Set(0.0),
            stability: ActiveValue::Set(0.0),
            last_review_date: ActiveValue::Set("".into()), // an entierly new item has no review date at all
            next_review_date: ActiveValue::Set("".into()),
            ..ActiveModelTrait::default()
        }
    }

    async fn before_save<C>(mut self, _db: &C, insert: bool) -> Result<Self, DbErr>
    where
        C: ConnectionTrait,
    {
        if insert {
            let item_type = self.item_type.take().ok_or(DbErr::Custom("New item had not 'item type' field, which is neccessary for the creation fo a new item!".into()))?;
            let uuid = Uuid::new_v4();
            let name = format!("{item_type}/{uuid}");
            let now = chrono::Utc::now().to_rfc3339();
            let url = format!("{item_type}://{name}");
            self.name = ActiveValue::Set(name);
            self.create_time = ActiveValue::Set(now.clone().into());
            self.update_time = ActiveValue::Set(now.into());
            self.url = ActiveValue::Set(url);
            self.item_type = ActiveValue::Set(item_type); // give the item type back plz
            Ok(self)
        } else {
            // we check that some of the fields have not been changed (invalid modification)
            // it is invalid to change the following fields:
            // 'name', 'create_time', 'item_type', 'url'
            // it is not possible to change these fields using the update endpoint
            if let ActiveValue::Set(_) = &self.name {
                return Err(DbErr::Custom("Invalid modification. Cannot change fields 'name', 'create_time', 'item_type' and 'url' after creation".into()));
            }
            let update_time = chrono::Utc::now().to_rfc3339();
            self.update_time = ActiveValue::Set(update_time);
            Ok(self)
        }
    }
}
