//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "review_item")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub name: String,
    #[sea_orm(column_type = "Double")]
    pub difficulty: f64,
    #[sea_orm(column_type = "Double")]
    pub stability: f64,
    pub last_review_date: String,
    pub url: String,
    pub data: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::review_event_log::Entity")]
    ReviewEventLog,
    #[sea_orm(has_many = "super::scheduled_review_event::Entity")]
    ScheduledReviewEvent,
}

impl Related<super::review_event_log::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ReviewEventLog.def()
    }
}

impl Related<super::scheduled_review_event::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ScheduledReviewEvent.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
