//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0-rc.7

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "tag_map")]
pub struct Model {
    pub tag_id: i32,
    pub item_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::review_item::Entity",
        from = "Column::ItemId",
        to = "super::review_item::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    ReviewItem,
    #[sea_orm(
        belongs_to = "super::tag::Entity",
        from = "Column::TagId",
        to = "super::tag::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Tag,
}

impl Related<super::review_item::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ReviewItem.def()
    }
}

impl Related<super::tag::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Tag.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
