#!/usr/bin/env zsh

if [[ -z $1 ]]; then
  echo "usage: edit_flashcard <item_id>"
  exit 1
fi

ID=$1

# optionally read in spbasedctl path from environment
if [[ -z $FLAKE_ROOT ]]; then
  # check that spbasedctl exist globally
  if which spbasedctl>/dev/null 2>&1; then
    SPBASEDCTL_BIN_="spbasedctl"
  else
    echo "SPBASEDCTL_BIN was unset and spbasedctl not found on PATH! exiting..."
    exit 1
  fi
else
  SPBASEDCTL_BIN_="$FLAKE_ROOT/target/debug/spbasedctl"
fi

FLASHCARD=$("$SPBASEDCTL_BIN_" items query --pre-filter="id==$ID && model=='flashcard'" --post-filter="[0].{id:id,data:data}")
FLASHCARD_ID=$(echo $FLASHCARD | jq ".id")
FLASHCARD_DATA=$(echo $FLASHCARD | jq ".data")

QUESTION=$(echo $FLASHCARD_DATA | jq -r ".question")
ANSWER=$(echo $FLASHCARD_DATA | jq -r ".answer")

QUESTION=$(gum write --placeholder="question" --value="$QUESTION")
ANSWER=$(gum write --placeholder="answer" --value="$ANSWER")

## Both question and answer must be set
if [[ -z "$QUESTION" || -z "$ANSWER" ]]; then
  echo "must provide non empty input"
  exit 1
fi

FLASHCARD=$(jq --compact-output --null-input --arg question $QUESTION --arg answer "$ANSWER" '.question = $question | .answer = $answer')

"$SPBASEDCTL_BIN_" items edit  --data "$FLASHCARD" "$ID"
