[package]
name = "model"
version = "0.1.0"
edition = "2021"

[dependencies]
sra = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
time = { workspace = true }
rusqlite = { workspace = true }
